language: python
python:
- '2.7'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
before_install:
- openssl aes-256-cbc -K $encrypted_677a56b8f0a8_key -iv $encrypted_677a56b8f0a8_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    secure: Nw4tfUD1P9sKp8M3BpE/GZmOnqitqsrypHelJ1UURT0v+jRrOHy4HhI77vKs2RRVSxsiKrGcwlcSnMwmkgNuQdaNASLtsaYjzm6Rtf6CHqzzc/Dy9DIxBXYC5oCkcsJLef1uGYfGFzXRum+NKAFuLsvNZbLiuE2rDeXSyBTZ9AnM1DYqAVd+k12s0T0Rca8Kw5vzyEOn35Rf4y2MjFdbs8NyuzFRLMuOVedNrEFJLioKNDKtglyh0lJ4uU9OjYASg1bJ8TgY1wBgcqSe6vA1CRB/1P0qDJiZdVNCTGmBGwBn9EbwivsA3nzcnfdQbPh2x2VKghrF8BzBJl6qDqBMZBo+Ag9Oc8kKy79BJahOOoJA1DwFYoleURK5vR0ksm2paSjKRbDeXcDcni45id4YVv1dOOGbFIF1EplvcTFNId7DiU/5cURb8NwuUnAF9Qubm7MRAzLvxajp5FEa4VYHtwyxMDP17WDMqh4aH/O/5ir8k31MqUCeJGer5pFUDI9ux8ipFpHCDJaVMqh/1uv+TXjP0cpuDlSdmJJxmdl305chtAeMxSPIGpn85ncrMNQfgfZnBFsDoPl9ePi86/c1kOHpSnLzKScFmj2c7VwKSxNdA6rJMG7rdSbdw8QUsGXVP4SCXRsjIWGlrMFxDtQ5CLnpLgnrVocAWsU/8fc0HdE=
